# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
deploy:
  docker:
    - image: cimg/base
  steps:
    - attach_workspace:
        at: my-site
    - run: ls -lah my-site
orbs:
  hugo: circleci/hugo@0.1
version: 2.1
workflows:
  main:
    jobs:
      - hugo/build:
          html-proofer: true
          version: '0.55'