version: 2.1 

aliases:
  defaults: &defaults
    docker:
      - image: lussier/hugo-aws-build:v0.74.3


jobs:
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: hugo
      - run: ./publish.sh

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master